### ISSUE TITLE
test result in containerized build is different compared to non-containerized build

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/taxonworks#2]
https://github.com/jhpoelen/taxonworks and associated https://github.com/jhpoelen/taxonworks-base provide a prototype to run TaxonWorks tests in a containerized environment using well-defined images (see https://travis-ci.org/jhpoelen/taxonworks). The goal of this is to reduce variability introduced by apt updates or other dependency differences pulled in during the travis build. Also, travis builds can be reproduced locally using publishes build images available through docker hub.

@mjy - I am noticing that the containerized build fails differently that the non-containerized build after merging the most recent changes. I figured you might recognize the test failures from previous occasions, so I am curious to hear your take on the differences described below. 

For example, the containerized build has 7 failures, at least one of which caused by a  PG::ForeignKeyViolations (see attached 451551648_log.txt and https://travis-ci.org/jhpoelen/taxonworks/builds/451551646 and https://travis-ci.org/jhpoelen/taxonworks/jobs/451551648)  while the non-containerized build (see 451519042_log.txt and https://travis-ci.org/SpeciesFileGroup/taxonworks/builds/451519041 and https://travis-ci.org/SpeciesFileGroup/taxonworks/jobs/451519042) has a single failure related to some UI element not being present (e.g., ```Failure/Error: fill_in 'session_email', with: email, wait: 10, id: 'session_emailCapybara::ElementNotFound:ESC[0m```).

The number of tests 6177 is the same across both builds. 

non-containerized [451519042_log.txt](https://github.com/jhpoelen/taxonworks/files/2555028/451519042_log.txt)

containerized [451551648_log.txt](https://github.com/jhpoelen/taxonworks/files/2555029/451551648_log.txt)

**Comment by jhpoelen** [comment]
PS Judging from comments in ./spec/features/otus_spec.rb (see snippet below), the failure in non-containerized build is known to happen from time to time.

```ruby
describe 'Otus', type: :feature do
  let(:index_path) { otus_path }
  let(:page_title) { 'Otus' }

  it_behaves_like 'a_login_required_and_project_selected_controller'

  context 'signed in as a user' do
    before do
      # TODO: Fix occasional "Capybara::ElementNotFound: Unable to find field "session_email" with id session_email"
      sign_in_user_and_select_project
      @user.generate_api_access_token
      @user.save!
    end
```

**Comment by mjy** [comment]
The session_email related errors are Capybara based timeouts we think, so that is not suprising that it appears from time to time.  The other errors should be identical in both worlds I would think, I can't think of why they would be different other than unsyncronized source code.
